// ============================================================
//  CardioSim 3D — Anatomy Data + Curves + Quiz + Guided Tour
// ============================================================

// ── ANATOMY DATABASE ──
export const ANATOMY = {
  'Left Ventricle': { title:'Left Ventricle', subtitle:'Chamber — Left Side', desc:'The most powerful chamber with walls up to 1.5 cm thick. Forms the apex (bottom tip) of the heart.', fn:'Pumps oxygen-rich blood through the aortic valve into the aorta, supplying the entire body with oxygenated blood.', blood:'Receives oxygenated blood from the left atrium via the mitral valve during diastole. Ejects it into the aorta during systole.', color:'#ff3355' },
  'Right Ventricle': { title:'Right Ventricle', subtitle:'Chamber — Right Side', desc:'Located anteriorly, with thinner walls than the left ventricle since it only pumps to the nearby lungs.', fn:'Pumps deoxygenated blood through the pulmonary valve into the pulmonary artery toward both lungs for gas exchange.', blood:'Receives deoxygenated blood from the right atrium via the tricuspid valve. Ejects it into the pulmonary circulation.', color:'#4488ff' },
  'Left Atrium': { title:'Left Atrium', subtitle:'Chamber — Left Side', desc:'A thin-walled receiving chamber positioned posteriorly. Receives blood from four pulmonary veins.', fn:'Collects freshly oxygenated blood returning from the lungs and passes it through the mitral valve into the left ventricle.', blood:'Oxygenated blood from pulmonary veins fills this chamber, then flows into the left ventricle during atrial contraction.', color:'#ff6b8a' },
  'Right Atrium': { title:'Right Atrium', subtitle:'Chamber — Right Side', desc:'Contains the SA node (natural pacemaker) in its wall. Receives all systemic venous return.', fn:'Collects deoxygenated blood from the entire body and passes it through the tricuspid valve into the right ventricle.', blood:'Deoxygenated blood enters via the superior vena cava (upper body) and inferior vena cava (lower body).', color:'#6ba8ff' },
  'Aorta': { title:'Aorta', subtitle:'Major Artery', desc:'The largest artery in the body (~2.5 cm diameter). Arches over the heart giving off three major branches.', fn:'Distributes oxygenated blood from the left ventricle to every organ and tissue in the body.', blood:'Carries high-pressure oxygenated blood. The aortic arch branches supply the head, neck, and arms.', color:'#ff3355' },
  'Pulmonary Artery': { title:'Pulmonary Artery', subtitle:'Major Artery', desc:'The only artery carrying deoxygenated blood. Bifurcates into left and right pulmonary arteries.', fn:'Transports deoxygenated blood from the right ventricle to both lungs for oxygenation and CO₂ removal.', blood:'Carries deoxygenated blood under lower pressure than the aorta, as lungs are close to the heart.', color:'#4488ff' },
  'Superior Vena Cava': { title:'Superior Vena Cava', subtitle:'Major Vein', desc:'Formed by junction of left and right brachiocephalic veins. Drains the upper body.', fn:'Returns deoxygenated blood from the head, neck, arms, and upper thorax to the right atrium.', blood:'Low-pressure deoxygenated venous blood flows passively into the right atrium.', color:'#4488ff' },
  'Inferior Vena Cava': { title:'Inferior Vena Cava', subtitle:'Major Vein', desc:'The largest vein in the body. Passes through the diaphragm to enter the right atrium from below.', fn:'Returns deoxygenated blood from the abdomen, pelvis, and lower extremities to the right atrium.', blood:'Carries the largest volume of venous return. Blood flow aided by skeletal muscle pump and breathing.', color:'#4488ff' },
  'Pulmonary Veins': { title:'Pulmonary Veins', subtitle:'Veins (×4)', desc:'Four veins (two from each lung) — the only veins carrying oxygenated blood in the body.', fn:'Transport freshly oxygenated blood from the lung capillaries back to the left atrium.', blood:'Carry oxygenated blood at low pressure. Empty into the posterior wall of the left atrium.', color:'#ff3355' },
  'Coronary Arteries': { title:'Coronary Arteries', subtitle:'Surface Vessels', desc:'The LCA and RCA branch from the aorta just above the aortic valve. Supply the heart muscle itself.', fn:'Provide the myocardium with its own blood supply. Blockage causes myocardial infarction (heart attack).', blood:'Branch into smaller arterioles penetrating the heart wall. Peak flow occurs during diastole when the muscle relaxes.', color:'#ff3355' },
  'Tricuspid Valve': { title:'Tricuspid Valve', subtitle:'AV Valve — Right', desc:'Three-leaflet valve anchored by chordae tendineae to papillary muscles in the right ventricle.', fn:'Prevents backflow of blood from the right ventricle into the right atrium during ventricular contraction.', blood:'Opens during diastole to allow passive and active filling of the right ventricle. Closes during systole.', color:'#ffcc00' },
  'Mitral Valve': { title:'Mitral (Bicuspid) Valve', subtitle:'AV Valve — Left', desc:'Two-leaflet valve. Most commonly affected valve in rheumatic heart disease. Also called bicuspid valve.', fn:'Prevents backflow from left ventricle to left atrium. Mitral prolapse/stenosis are common pathologies.', blood:'Opens during diastole for LV filling. Snaps shut during systole — first heart sound (S1 "lub").', color:'#ffcc00' },
  'Aortic Valve': { title:'Aortic Valve', subtitle:'Semilunar Valve', desc:'Three crescent-shaped cusps at the LV-aorta junction. Most common valve requiring surgical replacement.', fn:'Opens during systole to allow blood ejection into the aorta. Prevents regurgitation during diastole.', blood:'High-pressure valve. Closure produces second heart sound (S2 "dub"). Coronary arteries fill when it closes.', color:'#ffcc00' },
  'Pulmonary Valve': { title:'Pulmonary Valve', subtitle:'Semilunar Valve', desc:'Three cusps between right ventricle and pulmonary artery. Least commonly affected by disease.', fn:'Opens during RV systole to allow blood flow to lungs. Prevents backflow into the right ventricle.', blood:'Lower pressure than aortic valve. Pulmonary stenosis can obstruct blood flow to lungs in infants.', color:'#ffcc00' },
  'Septum': { title:'Interventricular Septum', subtitle:'Muscular Wall', desc:'Thick muscular wall dividing left and right ventricles. Prevents mixing of oxygenated and deoxygenated blood.', fn:'Maintains separation of systemic and pulmonary circulations. VSD (hole in septum) is a common congenital defect.', blood:'The left side contains oxygenated blood, the right side deoxygenated. Any opening causes shunting.', color:'#cc3355' },
  'SA Node': { title:'Sinoatrial (SA) Node', subtitle:'Electrical — Pacemaker', desc:'Cluster of specialized cells in the right atrial wall near the SVC opening. Fires at 60-100 impulses/min.', fn:'The heart\'s natural pacemaker. Generates rhythmic electrical impulses that initiate each heartbeat.', blood:'Well-supplied by the SA nodal artery (branch of RCA in 60% of people). Damage causes sick sinus syndrome.', color:'#00ffd5' },
  'AV Node': { title:'Atrioventricular (AV) Node', subtitle:'Electrical — Relay', desc:'Located at the interatrial septum near the tricuspid valve. Introduces a critical 0.1-second delay.', fn:'Delays the electrical signal from the SA node, ensuring atria finish contracting before ventricles begin.', blood:'Supplied by AV nodal artery. Acts as a backup pacemaker (40-60 bpm) if the SA node fails.', color:'#00ffd5' },
  'Bundle of His': { title:'Bundle of His & Purkinje Fibers', subtitle:'Electrical — Conduction', desc:'Specialized conducting fibers in the interventricular septum splitting into left and right bundle branches.', fn:'Rapidly conducts impulses from AV node to ventricular apex via Purkinje fibers, causing coordinated contraction from bottom up.', blood:'Ensures efficient ventricular ejection by activating the apex first, squeezing blood upward toward the outflow valves.', color:'#00ffd5' },
};

// ── GUIDED TOUR STEPS ──
export const GUIDED_STEPS = [
  { title:'Welcome to CardioSim 3D', text:'This interactive 3D heart model lets you explore every structure of the human heart. You can rotate, zoom, and click on any part. Let\'s begin a guided tour of blood circulation!', cam:[0,2,18] },
  { title:'Step 1: Deoxygenated Blood Returns', text:'Blood that has delivered oxygen to the body returns via the Superior and Inferior Vena Cava into the Right Atrium. This blood is low in oxygen (shown in blue).', cam:[6,4,14], highlight:'Right Atrium' },
  { title:'Step 2: Into the Right Ventricle', text:'Blood flows through the Tricuspid Valve into the Right Ventricle. The three leaflets of this valve prevent backflow when the ventricle contracts.', cam:[5,0,12], highlight:'Right Ventricle' },
  { title:'Step 3: To the Lungs', text:'The Right Ventricle pumps deoxygenated blood through the Pulmonary Valve into the Pulmonary Artery, which carries it to both lungs for gas exchange.', cam:[-6,5,12], highlight:'Pulmonary Artery' },
  { title:'Step 4: Gas Exchange', text:'In the lung capillaries, CO₂ is released and O₂ is absorbed. The now oxygen-rich blood (shown in red) returns via four Pulmonary Veins to the Left Atrium.', cam:[-5,4,-4], highlight:'Left Atrium' },
  { title:'Step 5: The Powerful Left Ventricle', text:'Blood passes through the Mitral Valve into the Left Ventricle — the strongest chamber. Its thick muscular walls generate the highest pressure in the heart.', cam:[-3,-1,14], highlight:'Left Ventricle' },
  { title:'Step 6: Out to the Body', text:'The Left Ventricle contracts powerfully, pushing blood through the Aortic Valve into the Aorta — the largest artery. From here, oxygenated blood reaches every cell in the body.', cam:[0,6,14], highlight:'Aorta' },
  { title:'Step 7: The Electrical System', text:'The SA Node initiates each heartbeat as an electrical impulse. It travels to the AV Node, down the Bundle of His, and through Purkinje Fibers — coordinating the synchronized contraction of all four chambers.', cam:[4,3,14], highlight:'SA Node' },
];

// ── QUIZ QUESTIONS ──
export const QUIZ = [
  { q:'Which chamber pumps oxygenated blood to the entire body?', opts:['Right Ventricle','Left Atrium','Left Ventricle','Right Atrium'], ans:2, explain:'The Left Ventricle is the strongest chamber, pumping oxygenated blood through the aorta.' },
  { q:'What is the heart\'s natural pacemaker?', opts:['AV Node','Bundle of His','Purkinje Fibers','SA Node'], ans:3, explain:'The SA Node generates 60-100 electrical impulses per minute, initiating each heartbeat.' },
  { q:'Which valve prevents backflow from the left ventricle to the left atrium?', opts:['Tricuspid','Aortic','Pulmonary','Mitral'], ans:3, explain:'The Mitral (bicuspid) Valve has two leaflets and guards the left AV opening.' },
  { q:'Which vessel carries deoxygenated blood from the heart to the lungs?', opts:['Aorta','Pulmonary Artery','Pulmonary Veins','Vena Cava'], ans:1, explain:'The Pulmonary Artery is the only artery carrying deoxygenated blood.' },
  { q:'What structure separates the left and right ventricles?', opts:['Septum','Pericardium','Endocardium','Myocardium'], ans:0, explain:'The interventricular septum prevents mixing of oxygenated and deoxygenated blood.' },
  { q:'Where does the coronary artery blood supply originate?', opts:['Pulmonary artery','Vena cava','Aorta (just above aortic valve)','Left atrium'], ans:2, explain:'Coronary arteries branch from the aorta just above the aortic valve, filling during diastole.' },
];

// ── CUSTOM 3D CURVES FOR VESSELS ──
import * as THREE from 'three';

export class AortaCurve extends THREE.Curve { getPoint(t) { const a=t*Math.PI*1.1; return new THREE.Vector3(Math.sin(a)*2.5-0.5, 3+Math.sin(a)*3.5, -Math.cos(a)*1.5+0.5); } }
export class PulmonaryArteryCurve extends THREE.Curve { getPoint(t) { return new THREE.Vector3(-1.5-t*2.5, 3+Math.sin(t*Math.PI)*2, 1.5-t*1.5); } }
export class SVCCurve extends THREE.Curve { getPoint(t) { return new THREE.Vector3(2.2+t*0.3, 2+t*5, -0.5-t*0.5); } }
export class IVCCurve extends THREE.Curve { getPoint(t) { return new THREE.Vector3(2.0+t*0.3, -1.5-t*4, -0.5-t*0.3); } }
export class PulmVeinCurve extends THREE.Curve { constructor(s){super();this.s=s;} getPoint(t) { return new THREE.Vector3(-2+this.s*t*2, 2.5+t*1.5+this.s*0.5, -1.5-t*2); } }
export class CoronaryLCA extends THREE.Curve { getPoint(t) { const a=t*Math.PI*1.5-0.5, r=3.2+Math.sin(t*4)*0.15; return new THREE.Vector3(Math.sin(a)*r*0.7-0.3, 2-t*5, Math.cos(a)*r*0.5); } }
export class CoronaryRCA extends THREE.Curve { getPoint(t) { const a=-t*Math.PI*1.2+0.5, r=3+Math.sin(t*3)*0.1; return new THREE.Vector3(Math.sin(a)*r*0.6+0.5, 1.5-t*4, Math.cos(a)*r*0.4+0.5); } }
export class BundleCurve extends THREE.Curve { constructor(s){super();this.s=s;} getPoint(t) { return new THREE.Vector3(this.s*t*1.5, 0.5-t*4, 0.2); } }
export class OxyFlowCurve extends THREE.Curve { getPoint(t) { const a=t*Math.PI; return new THREE.Vector3(Math.sin(a)*2.5-0.3, -1.5+t*9, -Math.cos(a)*1.5); } }
export class DeoxyFlowCurve extends THREE.Curve { getPoint(t) { return new THREE.Vector3(2-t*4, 5-t*3+Math.sin(t*Math.PI)*2, -0.5+t*2); } }
